[package]
name = "atlas-http-client"
version = "0.1.0"
edition = "2024"

[dependencies]
# local
atlas-core = { workspace = true }

# runtime
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

# client common
reqwest = { version = "0.12", features = ["rustls-tls"] }
